### ISSUE TITLE
Moebot motherboard

### ISSUE THREAD

**Issue by allaboutmikey** [Whytey/pymoebot#14]
Very interesting project Whytey. Apologies for using the issues to communicate. I couldn't figure out how else to contact you.
I have been toying with getting one of these moebots myself. Have you looked inside it to see what motherboard it uses? I was trying to figure out if it (and the similar ones you mention) could be a target for the [mowgli](https://github.com/cloudn1ne/Mowgli) project.

**Comment by Whytey** [comment]
Hi,

I've never opened up the sealed case. The only time I've seen any internal
is from someone on Facebook that was looking for power to run a GPS
tracker...

Sorry I'm not much help.

**Comment by Whytey** [comment]
![Uploading Screenshot_20230730-214911.png…]()

**Comment by Whytey** [comment]
Closing as not an issue

**Comment by Whytey** [comment]
![Screenshot_20230730-214911](https://github.com/Whytey/pymoebot/assets/876620/9bdb8964-3c8f-4b36-9780-763fe491dfb1)

**Comment by Whytey** [comment]
@allaboutmikey - I hope these help - https://github.com/Whytey/pymoebot/tree/main/images/internals

**Comment by allaboutmikey** [comment]
Very good, thanks. 
Is the writing on top of the biggest chip visible in real life? Completely unreadable in the photos unfortunately.
